image: image: registry.gitlab.com/kolanich/fixed_python:latest
stages:
  - dependencies
  - build
  - test
  - tooling

build:
  tags:
    - shared
  stage: build
  variables:
    GIT_DEPTH: "1"
    PYTHONUSERBASE: "${CI_PROJECT_DIR}/python_user_packages"
    SCIKIT_LEARN_DATA: "${CI_PROJECT_DIR}/scikit_learn_datasets"

  before_script:
    - export PATH="$PATH:$PYTHONUSERBASE/bin" # don't move into `variables`
    - pip3 install --user --pre --upgrade roman msgpack docutils scikit-learn
    - pip3 install --user --upgrade git+https://gitlab.com/KOLANICH/Chassis.py
    - pip3 install --user --upgrade git+https://github.com/Lukasa/hyper.git
    - pip3 install --user --upgrade git+https://github.com/coveralls-clients/coveralls-python.git@eba54e4d19e40e3907e5fd516f68e8b4dc9e5a31 git+https://github.com/codecov/codecov-python.git@0743daa83647f12ff31b84d07113d2c24c27b924 

  cache:
    paths:
      - "*.sqlite"
      - "$SCIKIT_LEARN_DATA"
      - "$PYTHONUSERBASE"

  script:
    - python3 setup.py bdist_wheel
    - pip3 install --user --upgrade ./dist/*.whl
    - coverage run --source=SurvivalDatasets ./tests/tests.py
    - mkdir wheels
    - mv ./dist/*.whl ./wheels/SurvivalDatasets-0.CI-py3-none-any.whl
    - coverage report -m
    - coveralls
    - codecov

  artifacts:
    paths:
      - wheels


checks:
  stage: test
  tags:
    - shared
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:dind
  script:
    - docker run --env SAST_CONFIDENCE_LEVEL=5 --volume "$PWD:/code" --volume /var/run/docker.sock:/var/run/docker.sock "registry.gitlab.com/gitlab-org/security-products/sast:latest" /app/bin/run /code
    #- docker run --env SOURCE_CODE="$PWD" --env CODECLIMATE_VERSION="latest" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock "registry.gitlab.com/gitlab-org/security-products/codequality:latest" /code
    #- docker run --env DEP_SCAN_DISABLE_REMOTE_CHECKS="${DEP_SCAN_DISABLE_REMOTE_CHECKS:-false}" --volume "$PWD:/code" --volume /var/run/docker.sock:/var/run/docker.sock "registry.gitlab.com/gitlab-org/security-products/dependency-scanning:latest" /code

  artifacts:
    reports:
      #codequality: gl-code-quality-report.json
      sast: gl-sast-report.json
      #dependency_scanning: gl-dependency-scanning-report.json